env:
  global:
  - CC_TEST_REPORTER_ID=1150314f608881da1441a004463b90348ac128104942e6cecc23f3d2e8cc49b1
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- py.test --cov poco_ops --cov-report=xml
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: pypi
  user: swf.operations
  password:
    secure: f2wCvmr5yyN0PoP+ILllAJKZs3JKzp8MH06PuP/mjHXno05jNjL6NvF1tvxK0epHviDK+ZbiimeuqxMNr0YPUjq3ZYeysI8yvvk0QyUam3T59e/yr0Nt2kWg3qR+BmvZJB3lB+C5//hdZYI+vsMYtlLyIikVcvB8g8D76HIycpPgdLf7upb+8A6qRncGQgfxXIzUSBwmPweomDJB986RYaN6vfs4gON6bUaysljkq8wTyW2CBhpktjPOnTZkJRb8zcuRpBBwTwM0z71jwJJrGj2KWk/hj+X8039iVudaP1OEwhSF39oZegIkinI5xWIQaJ+YAmCdsjowd70zpjJkczMvH3JV3VAKE91uHwA/JAeySphyzznZ971hXFx/BjvCQhXpMvG2w52Ngiuos3GuavcFbTQhaEZ6lIHPtPBECGUK+pVefpuDYju0sq0Z+cWnFFFysRs2cjTkNb0luKiNREu6UO7cPUt23Ii3F9+lC2+NknNgMXxuGNfP/KORoaQLvRQ8vpPpWgn6/tVOEqb+Zn4gmHhdGyj/sJ1pExaIU0rG8Ajd1gPgBWJrZi5r7cQS83jwxmhWPLVrnTvmN1hOdh75j5/E1ZsYtp+b6X+8wBcp1ryC05E4cLUweX2eIK3uSAs8rxce55Gmn0mY/pNIKx1gAeCDjRIMDj+oordVkTM=
  on:
    branch: master
    tags: true
    python: '3.6'
